%
% Generates the full file path for a list of filenames (obtained from
% 'dir') given with 'aFina' and 'dirNa' and saves the list to file 'sfn'.
% 
% IN  sfn    name of file to which the list of file names is saved
%     aFina  list of filenames as generated by 'dir' (field .name)
%     dirNa  directory name
%
function [] = SaveFinasFullDir(sfn, aFina, dirNa)

%% =====  Opening File  =====
fid = fopen(sfn, 'w');

if fid==-1, error('SaveFinasFullDir: could not write to %s\n', sfn); end
    
%% -----  Write Filenames  -----
for i = 1:length(aFina)
    fprintf(fid, '%s%s\n', dirNa, aFina(i).name);
end

%% =====  Close File  =====
fclose(fid);
    
% DispSave(sfn);

end

