%
% Generates and saves a list of filepaths (with names obtained from 'dir')
% as text with path from dir included.
% 
% IN  aFina  list of filenames as generated by 'dir' (field .name)
%     pth    path or directory 
%     sfn    name of file to which the list of file names is saved
%
% USE
%   aFinas     = dir( [pthBas.DescRef 'DSC_*.vec'] );
%   pthColl    = 'c:/CollImg/'
%   finaLst    = 'Finas.txt';
%   SaveFipaLstFromDir( aFinas, pthColl, finaLst );
%
function [] = SaveFipaLstFromDir( aFina, pth, sfn )

%% =====  Opening File  =====
fid = fopen(sfn, 'w');

if fid==-1, 
    error('SaveFinaLstFromDir: could not write to %s\n', sfn); 
end
    
%% -----  Write Filenames  -----
for i = 1:length(aFina)
    fprintf(fid, '%s%s\n', pth, aFina(i).name);
end

%% =====  Close File  =====
fclose(fid);
    
end

